[project]
name = "nutribr"
version = "0.1.0"
description = "Biblioteca nutricional com dados da TACO/IBGE"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
authors = [
  { name="Pedro Richil", email="seu-email@example.com" }
]
keywords = ["nutrição", "TACO", "IBGE", "alimentação", "nutrientes"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pedrorichil/nutribr"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
